services:
  - docker

language: go
go:
  - 1.8.x

script:
  - cp /etc/hosts /tmp/hosts
  - docker run --rm --entrypoint="/bin/sh"
    --volume="/tmp/hosts:/etc/hosts"
    lachlanevenson/k8s-kubectl -c 'echo >> /etc/hosts;
    echo "8.8.8.8 google.com" >> /etc/hosts;
    cat /etc/hosts'
  - docker run --rm --entrypoint="/bin/sh"
    --volume="/tmp/hosts:/etc/hosts"
    hashicorp/terraform -c 'echo >> /etc/hosts;
    echo "8.8.4.4 google.com" >> /etc/hosts;
    cat /etc/hosts'
